sudo: false

language: node_js

node_js:
  - 'stable'

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE igihe2;' -U postgres

env:
  - DATABASE_URL: postgres://localhost:5432/igihe2

cache:
  npm: false

notifications:
  email: false

script:
  - npm test
  - npm run coverage

after_success:
  - npm run coveralls
