sudo: false

language: node_js

node_js:
  - 'stable'

services:
  - postgresql

cache:
  npm: false

notifications:
  email: false

script:
  - npm test
  - npm run coverage

after_success:
  - npm run coveralls
